[default]
S3_ACCESS_KEY_ID = ""
S3_SECRET_ACCESS_KEY = ""
S3_REGION = ""
S3_Bucket = ""
S3_Key = ""
DATABASE_NAME = "backend"
DATABASE_USERNAME = "postgres"
AUTH_SERVER = "http://localhost:5984"
API_KEYS = ""

[DEVELOPMENT]
DATABASE_PASSWORD = "password"